server:
  httplisten:  "localhost:81"

log:
  encoding:       "json"
  outputpaths:
    - "log/app.log"
    - "stdout"
  level:          "debug"
  initialfields:
    app:          "redditclone"

db:
  pg:
    dialect:        "postgres"
    dsn:            "host=pg port=5401 dbname=postgres user=postgres password=postgres sslmode=disable"
    islogmode:      True
    isautomigrate:  True
  mongo:
    dsn:      "mongodb://root:root@mongo:27017"
    dbname:   "db"
  redis:
    addrs:
      - "redis:6379"
    login:    ""
    password: ""
    dbname:   0

repository:
  type:       "db"

jwtsigningkey: "LxsKJywDL5O5PvgODZhBH12KE6k2yL8E"
jwtexpiration: 72
sessionlifetime: 96
